// <auto-generated />
using System;
using ForgeDock.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ForgeDock.Infrastructure.Migrations
{
    [DbContext(typeof(ForgeDockDbContext))]
    [Migration("20261001210408_AutomaticRollback")]
    partial class AutomaticRollback
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ForgeDock.Domain.CustomDomain", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("CertificateExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("CertificateTrusted")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DnsVerifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Error")
                        .HasColumnType("text");

                    b.Property<string>("Hostname")
                        .IsRequired()
                        .HasMaxLength(253)
                        .HasColumnType("character varying(253)");

                    b.Property<DateTimeOffset>("NextCheckAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("VerificationRequested")
                        .HasColumnType("boolean");

                    b.Property<string>("VerificationToken")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Hostname")
                        .IsUnique();

                    b.HasIndex("ProjectId");

                    b.ToTable("CustomDomains");
                });

            modelBuilder.Entity("ForgeDock.Domain.DatabaseBackup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Error")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<string>("RemoteBucket")
                        .HasColumnType("text");

                    b.Property<string>("RemoteEndpoint")
                        .HasColumnType("text");

                    b.Property<string>("RemoteError")
                        .HasColumnType("text");

                    b.Property<string>("RemoteKey")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("RemoteNextAttemptAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RemoteRegion")
                        .HasColumnType("text");

                    b.Property<string>("RemoteState")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ServiceId")
                        .HasColumnType("uuid");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint");

                    b.Property<Guid?>("SourceBackupId")
                        .HasColumnType("uuid");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ServiceId", "CreatedAt");

                    b.ToTable("DatabaseBackups");
                });

            modelBuilder.Entity("ForgeDock.Domain.DatabaseService", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("BackupIntervalHours")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Error")
                        .HasColumnType("text");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("NextBackupAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<string>("ProtectedPassword")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId", "Kind")
                        .IsUnique();

                    b.ToTable("DatabaseServices");
                });

            modelBuilder.Entity("ForgeDock.Domain.Deployment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("AutoRollbackTriggeredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CommitAuthor")
                        .HasColumnType("text");

                    b.Property<string>("CommitMessage")
                        .HasColumnType("text");

                    b.Property<string>("CommitSha")
                        .HasColumnType("text");

                    b.Property<string>("ConfigurationJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ContainerId")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Error")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("HealthFailureCount")
                        .HasColumnType("integer");

                    b.Property<string>("ImageTag")
                        .HasColumnType("text");

                    b.Property<string>("LastStage")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Queued");

                    b.Property<Guid?>("PreviousDeploymentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<string>("ProtectedComposeManifest")
                        .HasColumnType("text");

                    b.Property<string>("RequestedCommit")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("RollbackDeadlineAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("RollbackSourceId")
                        .HasColumnType("uuid");

                    b.Property<string>("ServiceStatusJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("[]");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("State")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Trigger")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Manual");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("State");

                    b.HasIndex("ProjectId", "CreatedAt");

                    b.ToTable("Deployments");
                });

            modelBuilder.Entity("ForgeDock.Domain.DeploymentHook", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("DeploymentId")
                        .HasColumnType("uuid");

                    b.Property<int?>("ExitCode")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Output")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phase")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Truncated")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("DeploymentId", "StartedAt");

                    b.ToTable("DeploymentHooks");
                });

            modelBuilder.Entity("ForgeDock.Domain.MetricSample", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("BlockReadBytes")
                        .HasColumnType("bigint");

                    b.Property<long>("BlockWrittenBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("ContainerId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<double>("CpuPercent")
                        .HasColumnType("double precision");

                    b.Property<Guid>("DeploymentId")
                        .HasColumnType("uuid");

                    b.Property<long>("MemoryBytes")
                        .HasColumnType("bigint");

                    b.Property<long>("MemoryLimitBytes")
                        .HasColumnType("bigint");

                    b.Property<long>("NetworkReceivedBytes")
                        .HasColumnType("bigint");

                    b.Property<long>("NetworkSentBytes")
                        .HasColumnType("bigint");

                    b.Property<int>("Pids")
                        .HasColumnType("integer");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<string>("Service")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Timestamp");

                    b.HasIndex("ProjectId", "Timestamp");

                    b.ToTable("Metrics");
                });

            modelBuilder.Entity("ForgeDock.Domain.NotificationDelivery", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("DeploymentId")
                        .HasColumnType("uuid");

                    b.Property<string>("Error")
                        .HasColumnType("text");

                    b.Property<string>("Event")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("NextAttemptAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("SentAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.HasIndex("DeploymentId", "Event", "Channel")
                        .IsUnique();

                    b.ToTable("NotificationDeliveries");
                });

            modelBuilder.Entity("ForgeDock.Domain.NotificationSettings", b =>
                {
                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("EnabledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("OnFailure")
                        .HasColumnType("boolean");

                    b.Property<bool>("OnSuccess")
                        .HasColumnType("boolean");

                    b.Property<string>("ProtectedDiscordUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProtectedSlackUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ProjectId");

                    b.ToTable("NotificationSettings");
                });

            modelBuilder.Entity("ForgeDock.Domain.PreviewEnvironment", b =>
                {
                    b.Property<Guid>("ParentProjectId")
                        .HasColumnType("uuid");

                    b.Property<int>("Number")
                        .HasColumnType("integer");

                    b.Property<bool>("Closed")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("LastEventAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ProjectId")
                        .HasColumnType("uuid");

                    b.HasKey("ParentProjectId", "Number");

                    b.ToTable("PreviewEnvironments");
                });

            modelBuilder.Entity("ForgeDock.Domain.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ActiveDeploymentId")
                        .HasColumnType("uuid");

                    b.Property<string>("ApplicationName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("AutoRollbackEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("Branch")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BuildCommand")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ComposeFile")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ComposeService")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ContainerPort")
                        .HasColumnType("integer");

                    b.Property<double>("CpuLimit")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("double precision")
                        .HasDefaultValue(1.0);

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeploymentMode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Dockerfile")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EnvironmentName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("HealthPath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HealthStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("HookTimeoutSeconds")
                        .HasColumnType("integer");

                    b.Property<int>("MemoryLimitMiB")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(512);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid?>("ParentProjectId")
                        .HasColumnType("uuid");

                    b.Property<string>("PostDeployCommand")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PreDeployCommand")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("PreviewsEnabled")
                        .HasColumnType("boolean");

                    b.Property<int?>("PullRequestNumber")
                        .HasColumnType("integer");

                    b.Property<string>("RepositoryUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("ResourceAlertsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<int>("RollbackFailureThreshold")
                        .HasColumnType("integer");

                    b.Property<int>("RollbackWindowMinutes")
                        .HasColumnType("integer");

                    b.Property<string>("RootDirectory")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue(".");

                    b.Property<string>("StartCommand")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationName", "EnvironmentName")
                        .IsUnique();

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("ForgeDock.Domain.ProjectOperation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Error")
                        .HasColumnType("text");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("State");

                    b.ToTable("Operations");
                });

            modelBuilder.Entity("ForgeDock.Domain.ResourceAlert", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DeploymentId")
                        .HasColumnType("uuid");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId", "CreatedAt");

                    b.ToTable("ResourceAlerts");
                });

            modelBuilder.Entity("ForgeDock.Domain.ResourceObservation", b =>
                {
                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DeploymentId")
                        .HasColumnType("uuid");

                    b.Property<int>("ExitedChecks")
                        .HasColumnType("integer");

                    b.Property<bool>("OomObserved")
                        .HasColumnType("boolean");

                    b.Property<int>("RestartBaseline")
                        .HasColumnType("integer");

                    b.HasKey("ProjectId");

                    b.ToTable("ResourceObservations");
                });

            modelBuilder.Entity("ForgeDock.Domain.StorageCleanup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Error")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ResultJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("StorageCleanups");
                });

            modelBuilder.Entity("ForgeDock.Domain.StoragePolicy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("AutomaticCleanup")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LastCleanupAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("LogRetentionDays")
                        .HasColumnType("integer");

                    b.Property<int>("OrphanRetentionDays")
                        .HasColumnType("integer");

                    b.Property<int>("RetainedDeployments")
                        .HasColumnType("integer");

                    b.Property<int>("SourceRetentionDays")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("StoragePolicies");
                });

            modelBuilder.Entity("ForgeDock.Infrastructure.DeploymentLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<Guid>("DeploymentId")
                        .HasColumnType("uuid");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phase")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Build");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DeploymentId", "Id");

                    b.ToTable("Logs");
                });

            modelBuilder.Entity("ForgeDock.Infrastructure.ProjectEnvironment", b =>
                {
                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("ProtectedValue")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ProjectId", "Name");

                    b.ToTable("EnvironmentVariables");
                });

            modelBuilder.Entity("ForgeDock.Infrastructure.ProjectWebhook", b =>
                {
                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<string>("ProtectedSecret")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ProjectId");

                    b.ToTable("ProjectWebhooks");
                });

            modelBuilder.Entity("ForgeDock.Infrastructure.WebhookDelivery", b =>
                {
                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DeliveryId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("DeploymentId")
                        .HasColumnType("uuid");

                    b.Property<string>("Event")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("ProjectId", "DeliveryId");

                    b.HasIndex("ProjectId", "ReceivedAt");

                    b.ToTable("WebhookDeliveries");
                });

            modelBuilder.Entity("ForgeDock.Domain.CustomDomain", b =>
                {
                    b.HasOne("ForgeDock.Domain.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ForgeDock.Domain.DatabaseBackup", b =>
                {
                    b.HasOne("ForgeDock.Domain.DatabaseService", null)
                        .WithMany()
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ForgeDock.Domain.DatabaseService", b =>
                {
                    b.HasOne("ForgeDock.Domain.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ForgeDock.Domain.Deployment", b =>
                {
                    b.HasOne("ForgeDock.Domain.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ForgeDock.Domain.DeploymentHook", b =>
                {
                    b.HasOne("ForgeDock.Domain.Deployment", null)
                        .WithMany()
                        .HasForeignKey("DeploymentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ForgeDock.Domain.MetricSample", b =>
                {
                    b.HasOne("ForgeDock.Domain.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ForgeDock.Domain.NotificationDelivery", b =>
                {
                    b.HasOne("ForgeDock.Domain.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ForgeDock.Domain.NotificationSettings", b =>
                {
                    b.HasOne("ForgeDock.Domain.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ForgeDock.Domain.PreviewEnvironment", b =>
                {
                    b.HasOne("ForgeDock.Domain.Project", null)
                        .WithMany()
                        .HasForeignKey("ParentProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ForgeDock.Domain.ResourceAlert", b =>
                {
                    b.HasOne("ForgeDock.Domain.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ForgeDock.Domain.ResourceObservation", b =>
                {
                    b.HasOne("ForgeDock.Domain.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ForgeDock.Infrastructure.DeploymentLog", b =>
                {
                    b.HasOne("ForgeDock.Domain.Deployment", null)
                        .WithMany()
                        .HasForeignKey("DeploymentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ForgeDock.Infrastructure.ProjectEnvironment", b =>
                {
                    b.HasOne("ForgeDock.Domain.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ForgeDock.Infrastructure.ProjectWebhook", b =>
                {
                    b.HasOne("ForgeDock.Domain.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ForgeDock.Infrastructure.WebhookDelivery", b =>
                {
                    b.HasOne("ForgeDock.Domain.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
