import { useEffect, useRef, useState, type ReactNode } from 'react';
import { navigate } from './navigation';
import './docs.css';

type Section = { id: string; title: string; content: ReactNode };
type Article = { slug: string; title: string; summary: string; group: string; keywords: string; sections: Section[] };

function Code({ children, language = 'bash' }: { children: string; language?: string }) {
  const [copied, setCopied] = useState(false);
  const [failed, setFailed] = useState(false);
  const timer = useRef<ReturnType<typeof setTimeout> | undefined>(undefined);
  useEffect(() => () => clearTimeout(timer.current), []);
  async function copy() {
    try { await navigator.clipboard.writeText(children); setCopied(true); setFailed(false); }
    catch { setFailed(true); }
    clearTimeout(timer.current);
    timer.current = setTimeout(() => { setCopied(false); setFailed(false); }, 2000);
  }
  return <div className="docs-code"><div><span>{language}</span><button onClick={() => void copy()} aria-label="Copy code">{copied ? 'Copied ✓' : failed ? 'Select to copy' : 'Copy'}</button><span className="docs-sr" role="status">{copied ? 'Code copied to clipboard.' : failed ? 'Copy failed. Select the code to copy it manually.' : ''}</span></div><pre><code>{children}</code></pre></div>;
}
function Note({ children, title = 'Good to know' }: { children: ReactNode; title?: string }) {
  return <div className="docs-note"><span aria-hidden="true">i</span><div><strong>{title}</strong><div>{children}</div></div></div>;
}
function Link({ slug, children, className }: { slug: string; children: ReactNode; className?: string }) {
  const href = '/docs' + (slug ? '/' + slug : '');
  return <a href={href} className={className} aria-current={className === 'is-active' ? 'page' : undefined} onClick={event => navigate(event, href)}>{children}</a>;
}
const articles: Article[] = [
  { slug: '', title: 'Introduction', group: 'GETTING STARTED', summary: 'Your code. Your infrastructure. A clear path to production.', keywords: 'overview welcome platform architecture', sections: [
    { id: 'overview', title: 'Meet your deployment control room', content: <><p>ForgeDock turns public Git repositories into running applications on a Linux host you control. Connect a repository, choose how it builds, and follow every step from source to a healthy service.</p><div className="docs-flow"><span>01 <b>Connect</b><small>Public Git repository</small></span><i aria-hidden="true">→</i><span>02 <b>Build</b><small>Auto, Dockerfile, Compose</small></span><i aria-hidden="true">→</i><span>03 <b>Deploy</b><small>Health checks + routing</small></span></div></> },
    { id: 'start-here', title: 'Start here', content: <div className="docs-cards"><Link slug="quickstart"><span className="docs-card-icon">↗</span><h3>Get up and running</h3><p>Start your workspace locally with a single command.</p><span>Quickstart <b>→</b></span></Link><Link slug="automatic-builds"><span className="docs-card-icon">◇</span><h3>Deploy without a Dockerfile</h3><p>Let Railpack detect your application and build its image.</p><span>Automatic builds <b>→</b></span></Link><Link slug="first-deployment"><span className="docs-card-icon">▤</span><h3>Ship your first service</h3><p>Connect a repository and take it through a deployment.</p><span>First deployment <b>→</b></span></Link></div> },
    { id: 'how-it-works', title: 'Built around a simple workflow', content: <><p>The dashboard manages projects and deployment history. An API stores configuration in PostgreSQL, a worker builds and starts containers, and nginx sends traffic to your active application.</p><p>Single-application deployments switch traffic after HTTP health checks pass. If a new build fails, your existing route keeps serving its current version. Successful images are retained so you can restart or roll back.</p><Note title="A workspace you operate">This release is designed for one trusted operator on a single Linux host. Local routes use HTTP and bind to your machine. Public domains, managed TLS, team accounts, and private Git integrations are not included.</Note></> },
  ]},
  { slug: 'quickstart', title: 'Quickstart', group: 'GETTING STARTED', summary: 'Start your workspace and open the dashboard in minutes.', keywords: 'install setup run startup prerequisites linux node dotnet docker token', sections: [
    { id: 'prerequisites', title: 'Before you begin', content: <><p>You need a Linux machine with the following tools installed:</p><ul><li>.NET 10 SDK</li><li>Node.js 22.12 or newer, and npm</li><li>Docker Engine, running and accessible to your user</li><li>Git, Bash, Make, OpenSSL, curl, tar, sha256sum, install, and setsid</li></ul><p>The automatic-build installer supports x86_64 and aarch64 hosts.</p></> },
    { id: 'start-workspace', title: 'Start your workspace', content: <><p>From the repository directory, run:</p><Code>{"./scripts/start-local.sh"}</Code><p>The script creates your local configuration, starts PostgreSQL, nginx, and BuildKit, installs Railpack and frontend dependencies, applies database migrations, and launches the API, worker, and dashboard. Your existing <code>.env</code> is preserved.</p><Note title="First launch">The first run downloads dependencies and container images. Keep the terminal open while the workspace is running.</Note></> },
    { id: 'sign-in', title: 'Open the dashboard', content: <><p>Visit <a href="http://127.0.0.1:5173">http://127.0.0.1:5173</a>. Open your local <code>.env</code> file and use the <code>ForgeDock__ApiToken</code> value as your management token.</p><p>The token stays in browser memory for the current session. Documentation is available without signing in.</p><Link slug="first-deployment" className="docs-inline-link">Continue to your first deployment →</Link></> },
    { id: 'stop-workspace', title: 'Stop and start again', content: <><p>Press <kbd>Ctrl</kbd> + <kbd>C</kbd> in the startup terminal to stop the API, worker, and dashboard. Run the same script to start them again.</p><p>Infrastructure containers stay running. To stop those too:</p><Code>{"docker stop forgedock-proxy forgedock-postgres forgedock-buildkit"}</Code><p>Your database persists in the PostgreSQL volume. Keep your <code>.env</code> and secret key safe between launches.</p></> },
  ]},
  { slug: 'first-deployment', title: 'Your first deployment', group: 'GETTING STARTED', summary: 'Go from a repository URL to a running application.', keywords: 'project create git github public branch port health deploy route', sections: [
    { id: 'connect', title: '1. Connect your repository', content: <><p>In the dashboard, select <strong>New project</strong>. Give your application a name, enter its public HTTPS Git URL, and choose a branch, such as <code>main</code>.</p><p>URLs must not contain credentials. Private repositories and SSH cloning are not supported.</p></> },
    { id: 'configure', title: '2. Choose how it builds', content: <><p>Choose <strong>Auto</strong> for most single applications. ForgeDock uses your configured Dockerfile when present and otherwise builds with Railpack. Use <strong>Dockerfile</strong> to require a specific file, or <strong>Docker Compose</strong> for a multi-service stack.</p><p>Set <strong>Container port</strong> to the port your application listens on inside its container. Set an HTTP <strong>Health endpoint</strong> that responds successfully, such as <code>/</code> or <code>/health</code>.</p><Note title="Make it reachable">Your app must listen on <code>0.0.0.0</code>, rather than only localhost. Auto projects receive a runtime <code>PORT</code> matching the configured container port unless you explicitly save a different PORT variable.</Note></> },
    { id: 'deploy', title: '3. Build and deploy', content: <><p>Create the project, then select <strong>Deploy</strong>. The deployment history shows progress through cloning, building, starting, health checking, and routing. Open the logs to see the selected builder and application output.</p><p>When the deployment reaches <strong>Running</strong>, open the application route at the top of the project page.</p><Code language="text">{"http://<project-id-without-hyphens>.localhost:8088"}</Code></> },
    { id: 'next', title: 'What comes next', content: <><p>Save runtime variables in the <strong>Environment</strong> tab. Edit future deployment settings in <strong>Settings</strong>. To ship another version, push your changes to the repository and select <strong>Deploy</strong> again.</p><p>ForgeDock deploys on demand; Git push webhooks are not included.</p><Link slug="deployments" className="docs-inline-link">Learn about deployments and rollback →</Link></> },
  ]},
  { slug: 'automatic-builds', title: 'Automatic builds', group: 'BUILD & DEPLOY', summary: 'Ship supported applications without maintaining a Dockerfile.', keywords: 'railpack buildkit autodetect node python go rust dotnet build command start command PORT', sections: [
    { id: 'selection', title: 'Let your repository choose the builder', content: <><p>Choose <strong>Auto</strong> in your project settings. ForgeDock checks the configured Dockerfile path, which defaults to <code>Dockerfile</code>. If the file exists, Docker builds the image. If it is absent, Railpack detects the runtime and builds the image with BuildKit.</p><p>The build context is the repository root. Existing projects keep their saved build method; switching to Auto is an explicit settings change.</p><Note>Auto does not fall back after a Dockerfile build fails. Fix that build or remove the Dockerfile if you intend to use Railpack.</Note></> },
    { id: 'commands', title: 'Override build and start commands', content: <><p>Railpack detects dependencies and application commands from your repository. For custom workflows, set the optional <strong>Build command</strong> or <strong>Start command</strong> in ForgeDock. Leave them empty to use detection.</p><Code language="Project settings">{"Build command   npm run build\nStart command   node dist/server.js"}</Code><p>These fields apply to Railpack builds. You can also commit a <code>railpack.json</code> file for more advanced configuration. Dashboard command overrides take precedence over detection.</p><p>Unsupported projects or a missing start command fail with build logs. Review the <a href="https://railpack.com/" target="_blank" rel="noreferrer">Railpack language guides ↗</a> for your runtime.</p></> },
    { id: 'runtime', title: 'Configure the runtime', content: <><p>Auto projects receive <code>PORT</code> set to the configured container port. Your server should listen on <code>0.0.0.0</code> and read that variable. If you save your own <code>PORT</code> in Environment, make sure it matches the configured port.</p><Code language="JavaScript">{"server.listen(Number(process.env.PORT || 8080), '0.0.0.0');"}</Code><p>Environment variables saved in ForgeDock are available at runtime. They are not passed to Railpack during builds, so private dependencies and builds requiring secret values need additional integration.</p></> },
    { id: 'builder-setup', title: 'Prepare your worker', content: <><p>The startup script sets up Railpack and BuildKit. When starting services manually, run:</p><Code>{"make railpack\nmake worker"}</Code><p>The installer pins Railpack 0.40.1, verifies its release checksum, and starts a private, privileged BuildKit container on your trusted host. It publishes no host ports.</p><p>Operators can override the defaults in <code>.env</code>:</p><Code language=".env">{"ForgeDock__RailpackPath=/absolute/path/to/railpack\nForgeDock__BuildKitHost=docker-container://forgedock-buildkit"}</Code><p>See the <a href="https://railpack.com/reference/cli/" target="_blank" rel="noreferrer">official Railpack CLI reference ↗</a> for the underlying build commands.</p></> },
  ]},
  { slug: 'dockerfile', title: 'Dockerfile deployments', group: 'BUILD & DEPLOY', summary: 'Take full control over your application image.', keywords: 'docker build custom image monorepo Dockerfile paths context', sections: [
    { id: 'configure', title: 'Use your own Dockerfile', content: <><p>Select <strong>Dockerfile</strong> and set the repository-relative path, such as <code>Dockerfile</code> or <code>services/api/Dockerfile</code>. The worker builds it with the repository root as the Docker build context.</p><p>The configured file must exist. Absolute paths, parent traversal, and symbolic links in the Dockerfile path are rejected.</p></> },
    { id: 'example', title: 'A minimal Node application', content: <><Code language="Dockerfile">{"FROM node:22-alpine\nWORKDIR /app\nCOPY package*.json ./\nRUN npm ci --omit=dev\nCOPY . .\nENV PORT=8080\nEXPOSE 8080\nCMD [\"npm\", \"start\"]"}</Code><p>This example assumes a committed npm lockfile and a production start script. Your app must bind to <code>0.0.0.0:8080</code>; configure port <code>8080</code> in ForgeDock.</p></> },
    { id: 'runtime', title: 'Build once, run a healthy version', content: <><p>Dockerfile builds use the image's entrypoint and command. ForgeDock applies project variables at runtime and starts the container with resource limits, dropped capabilities, and no host-published application port. nginx reaches it over the managed Docker network.</p><p>A saved project variable is not automatically a Docker build argument. Include non-secret build configuration in the repository or Dockerfile as appropriate.</p></> },
  ]},
  { slug: 'compose', title: 'Docker Compose', group: 'BUILD & DEPLOY', summary: 'Deploy a stack with one public service and private dependencies.', keywords: 'multi service database postgres redis compose volumes persistent stack', sections: [
    { id: 'setup', title: 'Prepare Compose support', content: <><p>Install the private, checksum-verified Compose executable once:</p><Code>{"make compose"}</Code><p>Select <strong>Docker Compose</strong> in your project. Enter the repository-relative Compose file path, the public service name, and that service's internal port.</p></> },
    { id: 'routing', title: 'Choose the public service', content: <><p>Only the selected service receives application traffic through nginx. Other services communicate on the stack's private networks. ForgeDock removes host-published ports from the resolved Compose configuration.</p><Code language="Project settings">{"Compose file    compose.yaml\nPublic service  web\nContainer port  3000\nHealth endpoint /health"}</Code><p>Inspect the service status table in deployment history for each service's current state. Updates may briefly interrupt the stack.</p></> },
    { id: 'variables', title: 'Reference project variables', content: <><p>Save variables in ForgeDock and interpolate them in your Compose file:</p><Code language="yaml">{"services:\n  web:\n    build: .\n    environment:\n      DATABASE_URL: ${DATABASE_URL}"}</Code><p>Keep secrets in project variables rather than committing them. ForgeDock encrypts saved values and retained manifests at rest.</p></> },
    { id: 'volumes', title: 'Keep your data across deployments', content: <><p>Use supported named volumes for persistent data. They are retained when a project is deleted, so deleting a project does not erase your application's database volume.</p><p>Rollback restores the retained application version and variables. It does not reverse changes already made to a database or its schema.</p><Note title="Supported configuration">ForgeDock validates Compose manifests and rejects unsupported host access and configuration. Check deployment logs for validation errors before changing the stack.</Note></> },
  ]},
  { slug: 'environment', title: 'Environment variables', group: 'BUILD & DEPLOY', summary: 'Keep application configuration separate from your source code.', keywords: 'secrets encryption values PORT DATABASE_URL runtime build variables key', sections: [
    { id: 'save', title: 'Add a variable', content: <><p>Open the project's <strong>Environment</strong> tab. Enter a name, such as <code>DATABASE_URL</code>, and a single-line value, then select <strong>Save variable</strong>.</p><p>Names use letters, numbers, and underscores, and must start with a letter or underscore. Saved values are encrypted at rest and never returned by the management API.</p></> },
    { id: 'apply', title: 'Apply changes with a deployment', content: <><p>Changing or deleting a variable affects future deployments. Select <strong>Deploy</strong> to run the application with the new configuration.</p><p>Queued deployments keep a snapshot of their original settings and values. Restart and rollback use the retained version's snapshot rather than current project variables.</p><Note title="Runtime availability">Single-application variables are injected when the container starts. They are not available to Dockerfile or Railpack builds. Compose variables can be referenced with <code>{'${NAME}'}</code> in the manifest.</Note></> },
    { id: 'protect', title: 'Protect your workspace secrets', content: <><p>Keep your private <code>.env</code> out of version control. Back up <code>ForgeDock__SecretKey</code> with your database; existing encrypted values require the same key to decrypt.</p><p>Known project secret values are redacted from persisted logs. Avoid making your application print secrets or encode them into log output.</p></> },
  ]},
  { slug: 'deployments', title: 'Deployments & rollback', group: 'OPERATE', summary: 'Understand each deployment, inspect failures, and restore a version.', keywords: 'history stages logs failed running stopped restart rollback health previous image', sections: [
    { id: 'lifecycle', title: 'Follow the deployment lifecycle', content: <><p>A fresh deployment progresses through these stages:</p><Code language="Lifecycle">{"Queued \u2192 Preparing \u2192 Cloning \u2192 Building\n       \u2192 Starting \u2192 HealthChecking \u2192 Routing \u2192 Running"}</Code><p>Deployment history preserves the source commit, timestamps, state, and logs. Select a history item to inspect that version. A failure includes a reason and leaves the previous single-application route in place.</p></> },
    { id: 'logs', title: 'Read build and application logs', content: <><p>The log panel streams deployment output as the worker runs. Auto builds include a builder selection message so you can tell whether Dockerfile or Railpack was used.</p><p>Once a single application is running, the worker checks it periodically and collects recent container logs. Compose deployments also show service status.</p></> },
    { id: 'rollback', title: 'Roll back to a retained version', content: <><p>Choose an earlier successful deployment in history and select <strong>Roll back</strong>. ForgeDock starts its retained image with the original configuration and variables, checks health, and updates the route.</p><p>Rollback skips cloning and building. It requires the retained image to still exist on the worker. Database contents and schema changes are not rolled back.</p></> },
    { id: 'controls', title: 'Restart, stop, and delete', content: <><ul><li><strong>Restart</strong> creates a deployment from the active retained image and its saved settings.</li><li><strong>Stop</strong> stops the active application and removes its route.</li><li><strong>Delete</strong> removes project containers, routes, variables, and deployment history. Compose named data volumes are preserved.</li></ul><p>Retained images and source directories need separate operator cleanup. Wait for queued or active deployments to finish before stopping or deleting a project.</p></> },
  ]},
  { slug: 'health-routing', title: 'Health checks & routing', group: 'OPERATE', summary: 'Send traffic only after your application is ready.', keywords: 'port PORT 0.0.0.0 localhost nginx url route proxy health 60 seconds', sections: [
    { id: 'health', title: 'Configure a reliable health endpoint', content: <><p>Your health path must be a local absolute HTTP path, such as <code>/health</code>. Make it respond successfully when the application is ready to serve traffic.</p><p>For single applications, ForgeDock checks the container is running and retries HTTP checks for approximately 60 seconds. If the container exits or the check times out, the deployment fails.</p></> },
    { id: 'ports', title: 'Match the application port', content: <><p>The container port in Settings must match the server's actual listening port. Bind your server to <code>0.0.0.0</code>. Auto mode supplies a default runtime <code>PORT</code>; an explicitly saved PORT takes precedence.</p><div className="docs-table-wrap"><table><thead><tr><th>Local service</th><th>Address</th></tr></thead><tbody><tr><td>Dashboard & documentation</td><td><code>127.0.0.1:5173</code></td></tr><tr><td>Management API</td><td><code>127.0.0.1:5080</code></td></tr><tr><td>Application proxy</td><td><code>127.0.0.1:8088</code></td></tr><tr><td>PostgreSQL</td><td><code>127.0.0.1:5432</code></td></tr></tbody></table></div></> },
    { id: 'routes', title: 'Open your application route', content: <><p>Each project gets an HTTP route based on its ID:</p><Code language="text">{"http://<project-id-without-hyphens>.localhost:8088"}</Code><p>Use the application link in the dashboard after the deployment reaches Running. Local service ports bind to loopback. Public HTTPS domains and certificate management are not part of this release.</p></> },
  ]},
  { slug: 'troubleshooting', title: 'Troubleshooting', group: 'OPERATE', summary: 'Find the failing stage and get back to shipping.', keywords: 'errors failure docker unavailable missing railpack health timeout install buildkit database migrations', sections: [
    { id: 'startup', title: 'The workspace will not start', content: <><p>Check that the required commands are installed, Docker is running, and your user can access it:</p><Code>{"dotnet --version\nnode --version\ndocker info"}</Code><p>Make sure ports 5173, 5080, 8088, and 5432 are available. The startup script preserves your existing <code>.env</code>; verify it contains a valid connection string, token, secret key, and absolute runtime paths.</p></> },
    { id: 'build', title: 'An automatic build fails', content: <><p>Open deployment logs and find the first error. If Railpack is missing or BuildKit is unavailable, run <code>make railpack</code> on the worker host and retry.</p><Code>{"docker logs --tail 100 forgedock-buildkit"}</Code><p>If runtime detection fails, check Railpack's language guide. Add a start command when the application has a custom entrypoint. If your build needs secret values, remember that saved ForgeDock variables are available only at runtime.</p></> },
    { id: 'health', title: 'The application never becomes healthy', content: <><ul><li>Check that the server starts successfully and stays running.</li><li>Bind to <code>0.0.0.0</code> and match the configured container port.</li><li>Ensure the health path responds successfully without authentication.</li><li>Check required runtime variables and database connectivity.</li></ul><p>A saved <code>PORT</code> that differs from the container port is a common cause. Deployment logs show whether the container exited or HTTP checks failed.</p></> },
    { id: 'data', title: 'Migrations or encrypted values fail', content: <><p>Run <code>make migrate</code> with PostgreSQL running and a correct connection string. Back up the database and your original secret key together.</p><p>If you replaced <code>ForgeDock__SecretKey</code>, restore the original key to read existing encrypted values. Do not delete the PostgreSQL data volume to resolve a startup error.</p></> },
  ]},
];

export function Docs() {
  const [pathname, setPathname] = useState(window.location.pathname);
  const [query, setQuery] = useState('');
  const [menuOpen, setMenuOpen] = useState(false);
  const search = useRef<HTMLInputElement>(null);
  const slug = pathname.replace(/^\/docs\/?/, '').replace(/\/$/, '');
  const article = articles.find(item => item.slug === slug);
  const index = articles.findIndex(item => item.slug === slug);
  useEffect(() => {
    const onNavigation = () => { setPathname(window.location.pathname); setQuery(''); setMenuOpen(false); };
    const onKey = (event: KeyboardEvent) => {
      if ((event.metaKey || event.ctrlKey) && event.key.toLowerCase() === 'k') { event.preventDefault(); search.current?.focus(); }
      if (event.key === 'Escape') { setQuery(''); setMenuOpen(false); search.current?.blur(); }
    };
    window.addEventListener('popstate', onNavigation); window.addEventListener('keydown', onKey);
    return () => { window.removeEventListener('popstate', onNavigation); window.removeEventListener('keydown', onKey); };
  }, []);
  useEffect(() => { document.title = `${article?.title ?? 'Page not found'} · ForgeDock Docs`; }, [article]);
  const matches = query.trim() ? articles.filter(item => `${item.title} ${item.summary} ${item.keywords} ${item.sections.map(section => section.title).join(' ')}`.toLowerCase().includes(query.trim().toLowerCase())) : [];
  return <div className="docs-site">
    <a className="docs-skip" href="#docs-content">Skip to content</a>
    <header className="docs-header"><Link slug="" className="docs-brand"><span className="docs-logo" aria-hidden="true">◈</span>ForgeDock<span className="docs-brand-divider"/><span className="docs-brand-label">Docs</span></Link>
      <div className="docs-search"><span aria-hidden="true">⌕</span><input ref={search} aria-label="Search documentation" placeholder="Search documentation…" value={query} onChange={event => setQuery(event.target.value)} aria-controls={query.trim() ? 'docs-search-results' : undefined} /><kbd>⌘ / Ctrl K</kbd>
        {query.trim() && <div id="docs-search-results" className="docs-results" role="region" aria-label="Search results"><span className="docs-results-label">{matches.length} {matches.length === 1 ? 'RESULT' : 'RESULTS'}</span>{matches.map(item => <Link key={item.slug} slug={item.slug}><strong>{item.title}</strong><span>{item.summary}</span></Link>)}{!matches.length && <p>No pages found. Try “build”, “port”, or “environment”.</p>}</div>}
      </div><a className="docs-dashboard" href="/" onClick={event => navigate(event, '/')}>Open dashboard <span aria-hidden="true">↗</span></a><button className="docs-menu-toggle" aria-label="Toggle documentation navigation" aria-expanded={menuOpen} onClick={() => setMenuOpen(!menuOpen)}>☰</button>
    </header>
    <div className="docs-layout"><nav className={'docs-sidebar ' + (menuOpen ? 'is-open' : '')} aria-label="Documentation"><div className="docs-sidebar-top"><span className="docs-book" aria-hidden="true">▤</span><span>Documentation<small>Learn. Build. Ship.</small></span></div>{['GETTING STARTED', 'BUILD & DEPLOY', 'OPERATE'].map(group => <div className="docs-nav-group" key={group}><h2>{group}</h2>{articles.filter(item => item.group === group).map(item => <Link key={item.slug} slug={item.slug} className={item.slug === slug ? 'is-active' : ''}><span className="docs-nav-dot" aria-hidden="true"/>{item.title}</Link>)}</div>)}<div className="docs-sidebar-bottom"><span className="docs-status-dot"/>Self-hosted. In your control.<small>ForgeDock · Early release</small></div></nav>
    <main id="docs-content" className="docs-main" tabIndex={-1}>{article ? <><div className="docs-breadcrumb"><Link slug="">Documentation</Link><span>/</span><span>{article.title}</span></div><div className={'docs-article-heading ' + (!slug ? 'docs-hero' : '')}><span className="docs-eyebrow">{slug ? article.group : 'THE FORGEDOCK HANDBOOK'}</span><h1>{slug ? article.title : <>From repository<br/>to <em>running.</em></>}</h1><p>{slug ? article.summary : 'Everything you need to build, deploy, and operate applications on your own infrastructure.'}</p>{!slug && <div className="docs-hero-actions"><Link slug="quickstart" className="docs-primary-link">Start building <span aria-hidden="true">→</span></Link><Link slug="automatic-builds">Explore automatic builds <span aria-hidden="true">↗</span></Link></div>}</div>
      <article className="docs-article">{article.sections.map(section => <section key={section.id} id={section.id}><h2><a href={'#' + section.id}>{section.title}<span aria-hidden="true">#</span></a></h2>{section.content}</section>)}</article>
      <div className="docs-feedback"><span>Ready for the next step?</span><a href="/" onClick={event => navigate(event, '/')}>Open your workspace →</a></div><nav className="docs-pagination" aria-label="Adjacent documentation pages">{index > 0 ? <Link slug={articles[index - 1].slug}><span>← Previous</span><strong>{articles[index - 1].title}</strong></Link> : <div/>}{index < articles.length - 1 && <Link slug={articles[index + 1].slug}><span>Next →</span><strong>{articles[index + 1].title}</strong></Link>}</nav><footer className="docs-footer"><span>◈ ForgeDock</span><span>Built for the way you ship.</span></footer></> : <div className="docs-not-found"><span className="docs-eyebrow">404 · DOCUMENTATION</span><h1>This page sailed away.</h1><p>That documentation page does not exist. Find a guide in the sidebar or start at the introduction.</p><Link slug="" className="docs-primary-link">Back to documentation →</Link></div>}</main>
    {article && <nav className="docs-toc" aria-label="On this page"><span>ON THIS PAGE</span>{article.sections.map(section => <a href={'#' + section.id} key={section.id}>{section.title.replace(/^\d\. /, '')}</a>)}<div className="docs-toc-callout"><span aria-hidden="true">◇</span><strong>Less setup.<br/>More shipping.</strong><p>No Dockerfile? Start with an automatic build.</p><Link slug="automatic-builds">See how it works →</Link></div></nav>}</div>
  </div>;
}
