import { useEffect, useState } from 'react';
import { DeploymentFields, type DeploymentConfig } from './DeploymentFields';
import { navigate } from './navigation';
import { databaseKinds, databaseNames, type DatabaseKind } from './Databases';
type Api = <T>(path: string, body?: unknown, method?: string) => Promise<T>;
type Template = DeploymentConfig & { id: string; name: string; description: string; containerPort: number; healthPath: string; suggestedDatabase: DatabaseKind | null };
export function NewProject({ api, busy, onCreate, onCancel }: { api: Api; busy: boolean; onCreate: (request: unknown) => void; onCancel: () => void }) {
  const [templates, setTemplates] = useState<Template[]>([]), [selected, setSelected] = useState(''), [error, setError] = useState(''), [downloading, setDownloading] = useState(false), [database, setDatabase] = useState('');
  useEffect(() => { let active = true; void api<Template[]>('/templates').then(result => { if (active) setTemplates(result); }).catch(e => { if (active) setError((e as Error).message); }); return () => { active = false; }; }, [api]);
  const template = templates.find(template => template.id === selected);
  async function download() {
    if (!template) return; setDownloading(true); setError('');
    try { const blob = await api<Blob>(`/templates/${template.id}/archive`), url = URL.createObjectURL(blob); const link = document.createElement('a'); link.href = url; link.download = `forgedock-${template.id}-starter.zip`; link.click(); setTimeout(() => URL.revokeObjectURL(url), 1000); }
    catch (e) { setError((e as Error).message); } finally { setDownloading(false); }
  }
  return <><h1>Create a project</h1><p>Choose a common stack or configure your own repository. Templates set defaults you can edit before creating the project.</p><form className="panel form" onSubmit={event => {
    event.preventDefault(); const data = new FormData(event.currentTarget);
    onCreate({ name: data.get('name'), repositoryUrl: data.get('repository'), branch: data.get('branch'), dockerfile: data.get('dockerfile') ?? 'Dockerfile', deploymentMode: data.get('deploymentMode'), buildCommand: data.get('buildCommand') ?? '', startCommand: data.get('startCommand') ?? '', rootDirectory: data.get('rootDirectory') ?? '.', composeFile: data.get('composeFile') ?? 'docker-compose.yml', composeService: data.get('composeService') ?? '', containerPort: Number(data.get('port')), healthPath: data.get('health'), database: data.get('database') || null, acceptSqlServerLicense: data.get('sqlLicense') === 'on' });
  }}><label>Project template<select aria-label="Project template" value={selected} onChange={event => { setSelected(event.target.value); setDatabase(''); }}><option value="">Custom repository</option>{templates.map(template => <option key={template.id} value={template.id}>{template.name}</option>)}</select></label>
    {error && <p role="alert">{error}</p>}{template && <div className="template-note"><p>{template.description}</p><button className="secondary" type="button" disabled={downloading} onClick={() => void download()}>Download starter ZIP</button><p className="field-hint">Starting from scratch? Download the files, push them to your own GitHub repository, then paste its URL below. For existing apps, check that commands and endpoints match your code. <a href="/docs/project-templates" onClick={event => navigate(event, '/docs/project-templates')}>Template guide →</a></p></div>}
    <label>Project name<input name="name" required maxLength={100} placeholder="my-service" /></label><label>Repository URL<input name="repository" type="url" required placeholder="https://github.com/you/service.git" /></label><label>Branch<input name="branch" required defaultValue="main" /></label>
    <fieldset key={selected} className="template-fields"><DeploymentFields project={template} /><div className="columns"><label>Container port<input name="port" type="number" min={1} max={65535} required defaultValue={template?.containerPort ?? 8080} /></label><label>Health endpoint<input name="health" required defaultValue={template?.healthPath ?? '/'} /></label></div><label>Managed database<select aria-label="Managed database" name="database" value={database} onChange={event => setDatabase(event.target.value)}><option value="">None</option>{databaseKinds.map(kind => <option key={kind} value={kind}>{databaseNames[kind]}</option>)}</select></label>{database === 'SqlServer' && <><label className="checkbox-row"><input name="sqlLicense" type="checkbox" required />I accept the <a href="https://go.microsoft.com/fwlink/?LinkId=746388" target="_blank" rel="noreferrer">Microsoft SQL Server license terms</a>.</label><p className="field-hint">Free SQL Server Express requires an x86-64 host and 2 GiB memory.</p></>}{template?.suggestedDatabase && <p className="field-hint">{databaseNames[template.suggestedDatabase]} is a common choice for this stack. Adding it creates persistent storage and an encrypted connection variable.</p>}</fieldset>
    <div className="actions"><button disabled={busy}>Create project</button><button className="secondary" type="button" onClick={onCancel}>Cancel</button></div></form></>;
}
