import { useEffect, useState } from 'react';
import { navigate } from './navigation';
type Api = <T>(path: string, body?: unknown, method?: string) => Promise<T>;
type Settings = { enabled: boolean; previews: { id: string; name: string; branch: string; pullRequestNumber: number; healthStatus: string }[]; domains: { projectId: string; hostname: string }[] };
export function Previews({ projectId, branch, api }: { projectId: string; branch?: string; api: Api }) {
  const [settings, setSettings] = useState<Settings | null>(null), [error, setError] = useState(''), [busy, setBusy] = useState(false);
  async function refresh() { try { setSettings(await api<Settings>(`/projects/${projectId}/previews`)); } catch (e) { setError((e as Error).message); } }
  useEffect(() => { void refresh(); const timer = setInterval(() => void refresh(), 4000); return () => clearInterval(timer); }, [projectId, api]);
  return <section className="panel form"><div className="section-heading"><h2>Pull request previews</h2>{settings && <span className={'webhook-badge ' + (settings.enabled ? 'enabled' : '')}>{settings.enabled ? 'Enabled' : 'Disabled'}</span>}</div><p>Each pull request targeting this project's branch gets a separate deployment and URL. Closing or merging the pull request removes its preview.</p>{settings && !settings.enabled ? <aside className="preview-setup-note" role="note"><h3>Previews are disabled</h3><p>Pull requests will not create deployments until you enable previews and configure GitHub.</p><ol><li>Open <a href={`/projects/${projectId}/settings`} onClick={event => navigate(event, `/projects/${projectId}/settings`)}>project Settings</a> and enable <strong>GitHub auto-deploy</strong>. Set up its payload URL and secret in your repository's GitHub webhook.</li><li>In GitHub, edit that webhook, choose <strong>Let me select individual events</strong>, and select <strong>Pushes</strong> and <strong>Pull requests</strong>.</li><li>Click <strong>Enable previews</strong> below.</li><li>Open or update a non-draft pull request targeting <strong>{branch ?? 'the configured project branch'}</strong>. The next matching event creates the preview.</li></ol><a href="/docs/preview-environments" onClick={event => navigate(event, '/docs/preview-environments')}>Read the preview setup guide →</a></aside> : settings ? <p>Previews are enabled. Your GitHub webhook must send both <strong>Pushes</strong> and <strong>Pull requests</strong>. Open or update a non-draft PR targeting <strong>{branch ?? 'the configured project branch'}</strong> to trigger a preview. <a href="/docs/preview-environments" onClick={event => navigate(event, '/docs/preview-environments')}>Setup guide →</a></p> : <p>Loading preview settings…</p>}<p className="field-hint">Same-repository pull requests only; drafts and forks are skipped. Previews get fresh managed databases and their own environment variables. Production variables are never copied. Open a preview project to add any other configuration it needs.</p>{error && <p role="alert">{error}</p>}{settings && <><button disabled={busy} className={settings.enabled ? 'secondary' : ''} onClick={async () => { setBusy(true); setError(''); try { await api(`/projects/${projectId}/previews`, { enabled: !settings.enabled }, 'PUT'); await refresh(); } catch (e) { setError((e as Error).message); } finally { setBusy(false); } }}>{settings.enabled ? 'Disable previews' : 'Enable previews'}</button><p className="field-hint">Disabling pauses new previews. Existing previews are still removed when their pull requests close.</p>{settings.previews?.map(preview => {
    const domain = settings.domains?.find(domain => domain.projectId === preview.id); const url = domain ? `https://${domain.hostname}` : `http://${preview.id.replaceAll('-', '')}.localhost:8088`;
    return <article key={preview.id}><h3>PR #{preview.pullRequestNumber} · {preview.healthStatus}</h3><p>{preview.branch}</p><div className="actions"><a href={`/projects/${preview.id}/deployments`} onClick={event => navigate(event, `/projects/${preview.id}/deployments`)}>Open preview project →</a><a href={url} target="_blank" rel="noreferrer">Visit preview ↗</a></div></article>;
  })}</>}<p className="field-hint">Local URLs work on this machine. Public previews require a wildcard DNS record and the operator's ForgeDock__PreviewBaseDomain setting with HTTPS hosting configured.</p></section>;
}
