import { useEffect, useState } from 'react';
import { navigate } from './navigation';
type Api = <T>(path: string, body?: unknown, method?: string) => Promise<T>;
type Settings = { enabled: boolean; previews: { id: string; name: string; branch: string; pullRequestNumber: number; healthStatus: string }[]; domains: { projectId: string; hostname: string }[] };
export function Previews({ projectId, api }: { projectId: string; api: Api }) {
  const [settings, setSettings] = useState<Settings | null>(null), [error, setError] = useState(''), [busy, setBusy] = useState(false);
  async function refresh() { try { setSettings(await api<Settings>(`/projects/${projectId}/previews`)); } catch (e) { setError((e as Error).message); } }
  useEffect(() => { void refresh(); const timer = setInterval(() => void refresh(), 4000); return () => clearInterval(timer); }, [projectId, api]);
  return <section className="panel form"><h2>Pull request previews</h2><p>Each pull request targeting this project's branch gets a separate deployment and URL. Closing or merging the pull request removes its preview.</p><p>Enable GitHub auto-deploy in Settings, then edit your GitHub webhook to send both <strong>Pushes</strong> and <strong>Pull requests</strong>. Open or update a pull request to test.</p><p className="field-hint">Same-repository pull requests only; drafts and forks are skipped. Previews get fresh managed databases and their own environment variables. Production variables are never copied. Open a preview project to add any other configuration it needs.</p>{error && <p role="alert">{error}</p>}{settings && <><button disabled={busy} className={settings.enabled ? 'secondary' : ''} onClick={async () => { setBusy(true); setError(''); try { await api(`/projects/${projectId}/previews`, { enabled: !settings.enabled }, 'PUT'); await refresh(); } catch (e) { setError((e as Error).message); } finally { setBusy(false); } }}>{settings.enabled ? 'Disable previews' : 'Enable previews'}</button><p className="field-hint">Disabling pauses new previews. Existing previews are still removed when their pull requests close.</p>{settings.previews?.map(preview => {
    const domain = settings.domains?.find(domain => domain.projectId === preview.id); const url = domain ? `https://${domain.hostname}` : `http://${preview.id.replaceAll('-', '')}.localhost:8088`;
    return <article key={preview.id}><h3>PR #{preview.pullRequestNumber} · {preview.healthStatus}</h3><p>{preview.branch}</p><div className="actions"><a href={`/projects/${preview.id}/deployments`} onClick={event => navigate(event, `/projects/${preview.id}/deployments`)}>Open preview project →</a><a href={url} target="_blank" rel="noreferrer">Visit preview ↗</a></div></article>;
  })}</>}<p className="field-hint">Local URLs work on this machine. Public previews require a wildcard DNS record and the operator's ForgeDock__PreviewBaseDomain setting with HTTPS hosting configured.</p></section>;
}
