import { useEffect, useState } from 'react';
import { useUI } from './ui';
type Api = <T>(path: string, body?: unknown, method?: string) => Promise<T>;
type Data = { applicationName: string | null; environmentName: string | null; environments: { id: string; name: string; environmentName: string; healthStatus: string }[]; releases: { id: string; projectId: string; commitSha: string | null; createdAt: string }[] };
export function Releases({ projectId, api }: { projectId: string; api: Api }) {
  const [data, setData] = useState<Data>(), [application, setApplication] = useState(''), [environment, setEnvironment] = useState(''), [selected, setSelected] = useState(''), [error, setError] = useState(''), [busy, setBusy] = useState(false);
  const { confirm } = useUI();
  async function refresh(initial = false) { const result = await api<Data>(`/projects/${projectId}/releases`); setData(result); if (initial) { setApplication(result.applicationName ?? ''); setEnvironment(result.environmentName ?? ''); } }
  useEffect(() => { void refresh(true).catch(e => setError(e.message)); }, [projectId, api]);
  async function run(task: () => Promise<void>) { setBusy(true); setError(''); try { await task(); await refresh(); } catch (e) { setError((e as Error).message); } finally { setBusy(false); } }
  const releases = data?.releases.filter(r => r.projectId !== projectId) ?? [];
  return <section className="panel form"><h2>Environment groups and promotion</h2><p>Group independent projects as staging and production environments, then promote a retained image. This environment uses its own runtime variables, databases, domains, and resource limits. Build-time values remain part of the original image.</p>{error && <p role="alert">{error}</p>}
    <form onSubmit={e => { e.preventDefault(); void run(() => api(`/projects/${projectId}/releases/group`, { applicationName: application, environmentName: environment }, 'PUT')); }}><label>Application group<input maxLength={50} pattern="[a-z0-9-]+" value={application} onChange={e => setApplication(e.target.value)} placeholder="my-app" /></label><label>Environment name<input maxLength={50} pattern="[a-z0-9-]+" value={environment} onChange={e => setEnvironment(e.target.value)} placeholder="staging or production" /></label><button disabled={busy}>Save environment group</button></form>
    {data?.environments.map(e => <p key={e.id}><strong>{e.environmentName}</strong> · {e.name} · {e.healthStatus}</p>)}
    <h3>Promote into this environment</h3><p>Auto and Dockerfile apps can reuse a successful image from another environment with the same repository. The normal health checks run before routing changes.</p><label>Source release<select aria-label="Source release" value={selected} onChange={e => setSelected(e.target.value)}><option value="">Select a release</option>{releases.map(r => <option key={r.id} value={r.id}>{data?.environments.find(e => e.id === r.projectId)?.environmentName} · {r.commitSha?.slice(0, 7) ?? r.id.slice(0, 8)} · {new Date(r.createdAt).toLocaleString()}</option>)}</select></label><button disabled={busy || !selected} onClick={() => void run(async () => { if (await confirm({ title: 'Promote this release?', message: `Deploy the selected image into ${data?.environmentName ?? 'this environment'} with its saved runtime configuration. Build-time values stay in the image.`, label: 'Promote release' })) await api(`/projects/${projectId}/releases/promote`, { sourceDeploymentId: selected, confirm: true }); })}>Promote release</button>
  </section>;
}
