import { useEffect, useState } from 'react';
import { navigate } from './navigation';
type Api = <T>(path: string, body?: unknown, method?: string) => Promise<T>;
type Settings = { cpuLimit: number; memoryLimitMiB: number; alertsEnabled: boolean; alerts: { id: string; deploymentId: string; message: string; createdAt: string }[] };
export function Resources({ projectId, api }: { projectId: string; api: Api }) {
  const [settings, setSettings] = useState<Settings | null>(null), [error, setError] = useState(''), [busy, setBusy] = useState(false);
  async function refresh() { try { setSettings(await api<Settings>(`/projects/${projectId}/resources`)); } catch (e) { setError((e as Error).message); } }
  useEffect(() => { void refresh(); const timer = setInterval(() => void refresh(), 10000); return () => clearInterval(timer); }, [projectId, api]);
  return <section><h3>Resource controls</h3><p>Limits apply on the next deployment and are retained with that version. For Compose, these limits apply to the routed app service. Managed databases have their own fixed limits.</p>{error && <p role="alert">{error}</p>}{settings && <form onSubmit={async event => { event.preventDefault(); const data = new FormData(event.currentTarget); setBusy(true); setError(''); try { await api(`/projects/${projectId}/resources`, { cpuLimit: Number(data.get('cpu')), memoryLimitMiB: Number(data.get('memory')), alertsEnabled: data.has('alerts') }, 'PUT'); await refresh(); } catch (e) { setError((e as Error).message); } finally { setBusy(false); } }}>
    <label>CPU cores<input name="cpu" type="number" min={0.1} max={32} step={0.1} defaultValue={settings.cpuLimit} required /></label><label>Memory (MiB)<input name="memory" type="number" min={64} max={65536} step={1} defaultValue={settings.memoryLimitMiB} required /></label><label><input name="alerts" type="checkbox" defaultChecked={settings.alertsEnabled} /> Monitor crashes and resource pressure</label><button disabled={busy}>Save resource controls</button>
  </form>}<p className="field-hint">Apps restart up to five times after a failure. Alerts detect three crashes/restarts, an out-of-memory exit, or three usage samples above 90% of the quota. A one-hour cooldown limits repeats. Configure notification channels above for external alerts.</p>{settings?.alerts?.length ? <><h4>Recent resource alerts</h4>{settings.alerts.map(alert => <p key={alert.id}>{alert.message} <small>{new Date(alert.createdAt).toLocaleString()}</small> <a href={`/projects/${projectId}/deployments?deployment=${alert.deploymentId}`} onClick={event => navigate(event, `/projects/${projectId}/deployments?deployment=${alert.deploymentId}`)}>Logs →</a></p>)}</> : null}</section>;
}
